sudo: false
dist: trusty
language: rust
services:
- redis-server
os:
- linux
- osx
dist: trusty
osx_image: xcode8
rust: stable
env:
  global:
  - THERMITE_DEBUG_FILENAME: /tmp/thermite-debug.log
  matrix:
  - R_RUBY_VERSION: 2.3.3
  - R_RUBY_VERSION: 2.4.0

cache:
  cargo: true
  directories:
  - $TRAVIS_BUILD_DIR/vendor/bundle
  - $HOME/.cache/pip

before_install:
- |
  rvm install "$R_RUBY_VERSION"
  rvm use "$R_RUBY_VERSION"
  ruby --version
  if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! which bundle > /dev/null; then
    gem install bundler
  fi
- bundle install --jobs=3 --retry=3 --path=$TRAVIS_BUILD_DIR/vendor/bundle

before_script:
- |
  export PATH=$HOME/Library/Python/2.7/bin:$HOME/.local/bin:$PATH
  if [[ "$TRAVIS_OS_NAME" == "osx" ]] && ! which pip > /dev/null; then
    wget https://bootstrap.pypa.io/get-pip.py
    python get-pip.py --user
  fi
  pip install 'travis-cargo<0.2' --user

script:
- travis-cargo build
- bundle exec rake test
- bundle exec rake thermite:tarball
- bundle exec rake install
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    gem uninstall rusty_redic
    CARGO=fake bundle exec rake install
  fi
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    gem uninstall rusty_redic
    gem install minitest
    CARGO=fake gem install pkg/*.gem
    ruby test/test_rusty_redic.rb
  fi
- if [[ -f "$THERMITE_DEBUG_FILENAME" ]]; then cat $THERMITE_DEBUG_FILENAME; fi

deploy:
  provider: releases
  api_key:
    secure: kPF5xzVgW42igOf3AIqY1CGEn3Q4Dc9QEfdxkPlcSWsnHDSqDfdSqZn4yHsb8BFLtrR4Hd1QxerWVIKtitG5Mz/PX9i7vXzyXVNjX29vfWVvV4x9dqN4ZCcTHaU5MGMOqQ646fIdJZfzgMEaXztD3wFXOPxd1eBl3eBz1tDvOib9SnQF+qclbtdCJw8Q+LShOXQzzjplhfsGSJ7W1r8wtFiEHZILG88UCbJUneOo5YnL4lPQcF8m0/5N2aAO+Y1bcdK/zjygQdMQhqKPWVLrosnpY+2Y/Hs/6nzCi2PKuU0PPqEb7Ak8j9ikYKaNrlQCFBAsDZbPzfFdC9OlIQiURMsu2OIoUMb0F3sPGeTUAx4hvbI96XmCTsLb/+sySuRKQXwsN5D6gggnKZm/AhqA0mzKjjyUCPxLsLjittbQMCoRwdAIipkgfifrjqwnhzyjgf6FqYEJ/nFwkFP79GWk08mYzAsyqFlR0cdVn/LdJwazTu4DPbL2z+N0+C3rQeiysgvCOqrNv86inD36o9qMRPJq4dl08Add6Rd5qlNMHtoGNhKZJADawAR0o7fKhKOYHj5M6VWJPkY6TXE4g9QjfJ39qqWWZBrjbwZG5Z0zGYA2VZ/az4Avh8Uytfnc9Fjk+H+vy8xuXX6bACnUj/VVXy0H4+xS2+KZj157HFdD1mk=
  file: rusty_redic-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    condition: ${TRAVIS_TAG} =~ '-rust'
    repo: badboy/rusty_redic
    tags: true
notifications:
  email: false
